### ISSUE TITLE
3G device ports

### ISSUE THREAD

**Issue by bleucitron** [anthill/quipu#2]
You have to be carefull which ports you use on your 3G device depending on the application.
This can be tricky, because each model can have different ports, and for the same device, its ports can have different denomination depending on the OS you're on.

For example:

On Ubuntu, with a HUAWEI e3131 device, we have 3 different ports:
- ttyUSB0: for 3G connection (and apparently also sending sms, but not receiving)
- ttyUSB1: undefined for now
- ttyUSB2: for sending/receiving sms

On MacOS, for the same device:
- tty.HUAWEIMobile-Diag
- tty.HUAWEIMobile-Modem
- tty.HUAWEIMobile-Pcui

We are not sure which corresponds to which, but pcui might be USB2, and modem USB0. **This is to be confirmed**.

You need to pay attention on the port you're using for texting, and the one you're using for 3G connection (for now, in wvdial.conf).

**Comment by bleucitron** [comment]
I think i might have something that would solve this:
http://forum.ubuntu-fr.org/viewtopic.php?id=430477

**Comment by vallettea** [comment]
seems solid:
![screen shot 2015-06-16 at 17 42 31](https://cloud.githubusercontent.com/assets/371303/8187412/e91ead96-144f-11e5-8732-ea6983d46e51.png)

**Comment by bleucitron** [comment]
Closing !
